M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Τρι 24 Μαΐ 2022 09:45:02 μμ EEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-24T21:45:02+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X5.45Y-1.75
X5.45Y-3.9
X5.95Y-1.75
X6.45Y-1.75
X6.95Y-1.75
X7.45Y-1.75
X8.3Y-3.9
T0
M30
